### ISSUE TITLE
I have trained a hunyuanvideo lora, is there a lora weights merge script?

### ISSUE THREAD

**Issue by splinter21** [tdrussell/diffusion-pipe#15]
I'm running the inference script of hunyuanvideo official, but I need merge the lora weight into the whole weight first.

**Comment by splinter21** [comment]
![image](https://github.com/user-attachments/assets/d6b2bcc7-d86c-4124-ab3a-971f89d3bf13)
the lora weights are like this img

**Comment by splinter21** [comment]
layer_xx is the model weights
mp_rank_00_model_states.pt is the optimizer weights and other settings

**Comment by tdrussell** [comment]
These are the deepspeed checkpoint files. The lora weights will be a safetensors file in folders called epoch1, epoch2, etc.

There is no merge script currently. Most people are using the ComfyUI wrapper extention for loras. Diffusers doesn't have HunyuanVideo integration yet. But it is possible to do the merge manually with plain PEFT, you would just have to write the code yourself.

**Comment by splinter21** [comment]
@tdrussell is there a scaling_factor of lora for merging?

weight_merged=ori_weight+matmul(loraB,loraA)*scaling_factor

is the scaling_factor 1 if I use this lora traning scripts?

**Comment by splinter21** [comment]
> @tdrussell is there a scaling_factor of lora for merging?
> 
> weight_merged=ori_weight+matmul(loraB,loraA)*scaling_factor
> 
> is the scaling_factor 1 if I use this lora traning scripts?

it's 1

I have merged lora weights into the whole weights, and get the normal results.

**Comment by tdrussell** [comment]
The code forces lora alpha=rank, and doesn't allow changing it, so the scaling factor is always 1.

If you're curious, the reason for this is to simplify things and aid compatibility of the lora weights with downstream systems. For example, PEFT uses a JSON config file so it always knows what alpha is. But many programs like ComfyUI and Forge just load the safetensors, and rely on special scalar tensors for the alpha of each weight being present. But PEFT save functions, like e.g. Flux uses in this script, don't write alpha into the safetensors. So basically it's easy to mess something up, and have the safetensors lack the alpha values. But if you always force alpha=rank so the scaling factor is 1 it will always work and not lead to unexpected behavior.
