### ISSUE TITLE
multiple datasets

### ISSUE THREAD

**Issue by clementine-of-whitewind** [tdrussell/diffusion-pipe#19]
hello! I would like to define my own buckets, without ar_buckets, because I have different widths and heights that I would like to preserve, would it be possible to do multiple datasets similiar how to multiple eval_datasets are possible?

**Comment by tdrussell** [comment]
I'm not sure exactly what you're trying to do. Use some specific ar_buckets instead of the range-style specification? Not currently supported but easy to add. Just have different ar_buckets for different datasets? You should be able to set num_ar_buckets, min_ar, and max_ar per directory, i.e.
```
[[directory]]
path = '/home/anon/data/images/something'
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 9
```
If these fields are specified at the directory level they will override whatever is at the top level. Does this do what you want?

**Comment by clementine-of-whitewind** [comment]
Thank you for the reply! I suggested multiple datasets because that appeared simpler to me than functionality for specifying buckets.

yes, what I needed ideally is not ar_buckets as they currently are but completely self-specified ar_buckets.
for example, I had training data of 520x520x33, 520x320x33, 320x520x33, but using ar_buckets sets them to the pixel resolution of 512x512, even though I made the resolution and time-step as I already needed them.

my option then was either scale the 512x512 samples down to the same pixel-resolution as the other videos (which would involve figuring out what I would have to set in the ar_bucket value to properly have the 520x320 resolution) or accept that the 520x320 and 320x520 clips got scaled to 640x384 and 384x640

I like automated bucketing functionality, but personally I always make sure to have training data and buckets as I need them for balancing reasons and knowing on what I've trained exactly.

**Comment by tdrussell** [comment]
I pushed commit 3cd447dbd5f223c875e6dd8edf437aafaec37664 which I think supports your use case. You can directly specify the aspect ratios and resolutions using (width, height) pairs, and do so per-directory. For example:
```
[[directory]]
path = '/home/anon/data/something'
ar_buckets = [[512, 320]]
resolutions = [[512, 320]]
frame_buckets = [33]
```
Note that for these settings and all AR calculations, it's always width first in the pair (the opposite of how the tensor dimensions usually are).

**Comment by clementine-of-whitewind** [comment]
wow thanks a ton!
