### ISSUE TITLE
AssertionError: config must have _class_name=CausalVideoAutoencoder

### ISSUE THREAD

**Issue by TheresaXV** [tdrussell/diffusion-pipe#28]
nice work!
I built conda environment from requirements.txt
when i try to train LTXV lora, i got an error.
this is the output：
> [2024-12-22 19:47:40,725] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2024-12-22 19:47:43,549] [WARNING] [runner.py:212:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
> [2024-12-22 19:47:43,549] [INFO] [runner.py:585:main] cmd = /root/miniconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config config.toml
> [2024-12-22 19:47:45,321] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NCCL_IB_DISABLE=1
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NCCL_P2P_DISABLE=1
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.15.5-1+cuda11.8
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.15.5-1
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.15.5-1
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.15.5-1+cuda11.8
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
> [2024-12-22 19:47:48,095] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.15.5-1
> [2024-12-22 19:47:48,096] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
> [2024-12-22 19:47:48,096] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
> [2024-12-22 19:47:48,096] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
> [2024-12-22 19:47:48,096] [INFO] [launch.py:164:main] dist_world_size=1
> [2024-12-22 19:47:48,096] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
> [2024-12-22 19:47:48,097] [INFO] [launch.py:256:main] process 974 spawned with command: ['/root/miniconda3/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'config.toml']
> [2024-12-22 19:47:49,916] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2024-12-22 19:47:53,563] [INFO] [comm.py:652:init_distributed] cdb=None
> [2024-12-22 19:47:53,563] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/root/diffusion-pipe/train.py", line 209, in <module>
> [rank0]:     model = ltx_video.LTXVideoPipeline(config)
> [rank0]:   File "/root/diffusion-pipe/models/ltx_video.py", line 63, in __init__
> [rank0]:     vae = load_vae(ckpt_dir / 'vae', dtype)
> [rank0]:   File "/root/diffusion-pipe/models/ltx_video.py", line 30, in load_vae
> [rank0]:     vae = CausalVideoAutoencoder.from_config(vae_config)
> [rank0]:   File "/root/diffusion-pipe/submodules/LTX-Video/ltx_video/models/autoencoders/causal_video_autoencoder.py", line 65, in from_config
> [rank0]:     config["_class_name"] == "CausalVideoAutoencoder"
> [rank0]: AssertionError: config must have _class_name=CausalVideoAutoencoder
> [2024-12-22 19:47:56,106] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 974
> [2024-12-22 19:47:56,106] [ERROR] [launch.py:325:sigkill_handler] ['/root/miniconda3/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'config.toml'] exits with return code = 1

and my config.toml:

> # Dataset config file.
> output_dir = '~/training_output'
> dataset = 'dataset.toml'
> 
> # Training settings
> epochs = 50
> micro_batch_size_per_gpu = 1
> pipeline_stages = 1
> gradient_accumulation_steps = 4
> gradient_clipping = 1.0
> warmup_steps = 100
> 
> # eval settings
> eval_every_n_epochs = 5
> eval_before_first_step = true
> eval_micro_batch_size_per_gpu = 1
> eval_gradient_accumulation_steps = 1
> 
> # misc settings
> save_every_n_epochs = 5
> checkpoint_every_n_minutes = 30
> activation_checkpointing = true
> partition_method = 'parameters'
> save_dtype = 'bfloat16'
> caching_batch_size = 1
> steps_per_print = 1
> video_clip_mode = 'single_middle'
> 
> [model]
> type = 'ltx-video'
> diffusers_path = '/root/autodl-tmp/LTX-Video'
> dtype = 'bfloat16'
> transformer_dtype = 'bfloat16'
> timestep_sample_method = 'logit_normal'
> 
> [adapter]
> type = 'lora'
> rank = 64
> dtype = 'bfloat16'
> 
> [optimizer]
> type = 'adamw_optimi'
> lr = 5e-5
> betas = [0.9, 0.99]
> weight_decay = 0.02
> eps = 1e-8
> 
> 
> # Resolution settings.
> # Can adjust this to 1024 for image training, especially on 24gb cards.
> resolutions = [512]
> 
> # Aspect ratio bucketing settings
> enable_ar_bucket = true
> min_ar = 0.5
> max_ar = 2.0
> num_ar_buckets = 7
> 
> # Frame buckets (1 is for images)
> frame_buckets = [1]
> 
> [[directory]]
> # Set this to where your dataset is
> path = '~/dataset_v1'
> # Reduce as necessary
> num_repeats = 5

Could you check it for me? Thank you very much!

**Comment by tdrussell** [comment]
There have been some changes in the Huggingface LTX-Video model and configs that have broken things. I just made a change that switches to the Diffusers implementation for LTX-Video. Make sure you're using the latest version of the [LTX-Video](https://huggingface.co/Lightricks/LTX-Video) model. And update all the requirements (```pip install -r requirements.txt -U```).

Also keep in mind the following:
1. I haven't done any testing of these new LTX-Video changes beyond running a few training steps and verifying that the loss values look approximately correct.
2. How are you going to use the LoRA for inference? Raw PEFT? Diffusers? ComfyUI? I'm not sure if Diffusers or ComfyUI supports the LoRAs out of the box. You will have to check. The LoRA format output by this training script should follow the Diffusers convention for state_dict key formats.
