### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by gsiisg** [tdrussell/diffusion-pipe#37]
I'm probably running out of memory, but I don't see how, as I am only training 2 jpg each 512x512 with .txt with same filenames.  I'm at my wit's end, solving many issues over the last two days and countless hours trying to get this to work, finally giving up asking for help here. I have a 4090 24GB, WSL following instructions from https://civitai.com/articles/9798/training-a-lora-for-hunyuan-video-on-windows

message I got:

using video_clip_mode=single_middle
caching metadata
num_proc must be <= 2. Reducing num_proc to 2 for dataset of size 2.
Map: 100%|████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 293.17 examples/s]
caching latents: /home/rapids/mounted/hunyuan_lora_train/goku
caching latents: (1.0, 1)
caching latents: (512, 512, 1)
num_proc must be <= 2. Reducing num_proc to 2 for dataset of size 2.
caching text embeddings: (1.0, 1)
num_proc must be <= 2. Reducing num_proc to 2 for dataset of size 2.
Map (num_proc=2):   0%|                                                                    | 0/2 [00:00<?, ? examples/s]time="2024-12-24T20:29:10-08:00" level=error msg="error waiting for container: unexpected EOF"

config.toml
```
# Dataset config file.
output_dir = '/home/rapids/mounted/hunyuan_lora_train/models'
dataset = 'dataset.toml'

# Training settings
epochs = 50
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 4
gradient_clipping = 1.0
warmup_steps = 100

# eval settings
eval_every_n_epochs = 5
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 5
checkpoint_every_n_minutes = 30
activation_checkpointing = true
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 1
video_clip_mode = 'single_middle'

[model]
type = 'hunyuan-video'
transformer_path = '/home/rapids/mounted/hunyuan_lora_train/hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors'
vae_path = '/home/rapids/mounted/hunyuan_lora_train/wrapper_hunyuan_video_vae_bf16.safetensors'
llm_path = 'Kijai/llava-llama-3-8b-text-encoder-tokenizer'
clip_path = 'openai/clip-vit-large-patch14'
dtype = 'bfloat16'
transformer_dtype = 'float8'
timestep_sample_method = 'logit_normal'

[adapter]
type = 'lora'
rank = 64
dtype = 'bfloat16'

[optimizer]
type = 'adamw_optimi'
lr = 5e-5
betas = [0.9, 0.99]
weight_decay = 0.02
eps = 1e-8
```

dataset.toml
```
# Resolution settings.
# Can adjust this to 1024 for image training, especially on 24gb cards.
resolutions = [512]

# Aspect ratio bucketing settings
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7

# Frame buckets (1 is for images)
frame_buckets = [1]

[[directory]]
# Set this to where your dataset is
path = '/home/rapids/mounted/hunyuan_lora_train/goku'
# Reduce as necessary
num_repeats = 5
```

following suggestion at https://github.com/tdrussell/diffusion-pipe/issues/9 I have .wslconfig
```
[wsl2]
localhostForwarding=true
memory=24GB
swap=30GB
[experimental]
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
sparseVhd=true
autoMemoryReclaim=gradual
```

**Comment by rkfg** [comment]
The actual error is `error waiting for container: unexpected EOF`, looks like something docker-related. If you use a container try without it (just conda would do) or check docker's logs for details.

**Comment by gsiisg** [comment]
That was it, thank you @rkfg , I assumed that wsl requires docker, but just using wsl worked after re-doing all the steps in the guide.  The wsl ran into issues with folder/file permission issues with the location I was using, so I think docker encountered the same problem but the error message was lost/hidden through the docker layer, so it was harder to debug, after solving the permission issue it worked.
