### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for AutoencoderKLCausal3D

### ISSUE THREAD

**Issue by dropmasta** [tdrussell/diffusion-pipe#43]
I get an RuntimeError: Error(s) in loading state_dict for AutoencoderKLCausal3D when using the hunyuan training script.

**Comment by dropmasta** [comment]
![Screenshot 2024-12-28 114159](https://github.com/user-attachments/assets/3b226612-5322-4ec0-9fa6-8ba17834a0eb)

**Comment by webbigdata-jp** [comment]
I got the same error message.

But I was able to avoid it by using hunyuan_video_vae_fp32.safetensors
instead of hunyuan_video_vae_bf16.safetensors.

I haven't been able to get it to work yet either, but please keep trying.

**Comment by lebeastmode** [comment]
yes this is the fix for me as well thanks
