### ISSUE TITLE
FileNotFoundError:` No such file or directory: on WSL2

### ISSUE THREAD

**Issue by lebeastmode** [tdrussell/diffusion-pipe#44]
I'm following this article for reference [https://civitai.com/articles/9798/training-a-lora-for-hunyuan-video-on-windows]

I'm getting 
`FileNotFoundError:` No such file or directory: "~/diffusion-pipe/models/hunyuan/hunyuan_video_vae_bf16.safetensors"`

How do I edit the config file to point to the right folder?

**Comment by dropmasta** [comment]
You have to edit the examples/hunyuan_video.toml and point it to right folder where the checkpoints are. It's working for me now, but i am using linux.

**Comment by lebeastmode** [comment]
Ok but the right folder is "~/diffusion-pipe/models/hunyuan/hunyuan_video_vae_bf16.safetensors" so im confused

**Comment by seruva19** [comment]
If you are using WSL, then it might be easier to use absolute paths. For example, if your Windows path to the VAE is:
`E:/diffusion-pipe/models/hunyuan/hunyuan_video_vae_bf16.safetensors`

Then in WSL config you can write it as:
`vae_path = '/mnt/e/diffusion-pipe/models/hunyuan/hunyuan_video_vae_bf16.safetensors'`

**Comment by lebeastmode** [comment]
getting
`[rank0]: FileNotFoundError: No such file or directory: "/mnt/c/diffusion-pipe/models/hunyuan/hunyuan_video_vae_bf16.safetensors"`

if it helps the windows explorer to the correct path shows
`\\wsl.localhost\Ubuntu\home\ubuntu\diffusion-pipe\models\hunyuan`

**Comment by seruva19** [comment]
Try to run this bash command, it should give exact location of vae inside Ubuntu file system:
`find / -name "hunyuan_video_vae_bf16.safetensors`

**Comment by lebeastmode** [comment]
ok that worked. but now I get a different error.
`[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/diffusion-pipe/train.py", line 212, in <module>
[rank0]:     model = hunyuan_video.HunyuanVideoPipeline(config)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/diffusion-pipe/models/hunyuan_video.py", line 226, in __init__
[rank0]:     vae.load_state_dict(vae_sd)
[rank0]:   File "/home/ubuntu/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for AutoencoderKLCausal3D:
[rank0]:        Missing key(s) in state_dict:`

**Comment by seruva19** [comment]
Look like the same error as #43

**Comment by lebeastmode** [comment]
ok ill close it and go to that thread thanks
