### ISSUE TITLE
Installed DeepSpeed 0.16.1 on windows but error when training Lora.

### ISSUE THREAD

**Issue by QNM156** [tdrussell/diffusion-pipe#46]
I was able to install deepspeed on windows but get an invalid scalar type error when trying to train a lora. Is the training more geared for linux?

**Comment by alisson-anjos** [comment]
It is written in the project's README, deepspeed does not have full support on windows, the solution is to use WSL 2 or a docker (there is a fork that I made a docker + an interface with gradio), take a look at the forks if you want to use docker.

**Comment by QNM156** [comment]
fair enough. I was hoping it might work because I was able to compile deepspeed using the program here: https://github.com/erew123/deepspeedpatcher
I will try it in WSL 2 as I already have a comfyui Hunyuan setup there.
Thanks.
