### ISSUE TITLE
if your script supports lora fine-tuning hunyuanvideo and is being used independently.

### ISSUE THREAD

**Issue by WangRongsheng** [tdrussell/diffusion-pipe#5]
Hi, I would like to know if your script supports lora fine-tuning hunyuanvideo and is being used independently, in fact I am not very good at using ComfyUI. i think it is important to be able to train and reason independently about hunyuanvideo.

**Comment by tdrussell** [comment]
Are you asking if the LoRAs work outside the HunyuanVideoWrapper ComfyUI extension? Right now, there's no Diffusers integration for HunyuanVideo. So I don't think there's an easy one-liner to load a lora on the model. But, you can always directly use PEFT to set up a lora on the transformer, then load the lora state_dict into the weights. You may need several lines of custom code though, and you would have to handle the state_dict key format correctly.

**Comment by WangRongsheng** [comment]
please check https://github.com/huggingface/diffusers/pull/10136
thank you
