### ISSUE TITLE
Can't find llava-llama-3-8b-text-encoder-tokenizer

### ISSUE THREAD

**Issue by popovidis** [tdrussell/diffusion-pipe#7]
Hi there, I am trying to find this:
![image](https://github.com/user-attachments/assets/98306a37-7684-461d-ba80-fb3fa0d1ca91)

Am I supposed to download everything from here: https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer/tree/main ?

**Comment by Bocchi-Chan2023** [comment]
yes. clone and select it.

**Comment by popovidis** [comment]
> yes. clone and select it.

![image](https://github.com/user-attachments/assets/6045dc4f-23ac-4ab5-8cae-2fd14b905f1f)

which one?

**Comment by Bocchi-Chan2023** [comment]
**Clone**

**Comment by rayryeng** [comment]
Just for the sake of closure, clone means to *copy everything*. The easiest is to use the Git link provided on that page and clone the repo.

**Comment by joytsay** [comment]
`git clone https://huggingface.co/Kijai/llava-llama-3-8b-text-encoder-tokenizer`
